steps:
- name: Checkout repository
  uses: actions/checkout@v3

- name: Configure SSH
  run: |
    mkdir -p ~/.ssh
    echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

- name: SSH and deploy
  run: |
    ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_INSTANCE_ID }} << 'EOF'
      cd /home/ubuntu
      if [ ! -d "my-app" ]; then
        git clone https://github.com/dheerendrabhandari8/kubernetes-role.git my-app
      else
        cd my-app
        git pull origin main
      fi

      cd my-app
      # Optional build/deploy steps:
      # npm install
      # pm2 restart app
    EOF
