name: Clone repo on AWS EC2

on: [push]
  

jobs:
  clone-on-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo (not strictly necessary unless you need files)
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H 65.1.112.12 >> ~/.ssh/known_hosts

      - name: Clone target repo on EC2 instance
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@65.1.112.12 "git clone https://github.com/dheerendrabhandari8/kubernetes-role.git ~/cloned-repo && ls -la ~/cloned-repo"